- warn: {name: Use explicit module export list}
- group: {name: dollar, enabled: true}
- group: {name: teaching, enabled: true}
- group: {name: generalise-for-conciseness, enabled: true}
- group: {name: future, enabled: true}
- ignore: {name: Use infix}
