name:                json-search
version:             0.1.0.0
github:              "webdevred/json-search"
license:             BSD-3-Clause
author:              "webdevred"
maintainer:          "example@example.com"
copyright:           "2024 August Johansson"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/json-search#readme>

dependencies:
- base >= 4.7 && < 5
- relude
- bytestring
- utf8-string
- aeson
- vector
- text
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-imports
- -XNoImplicitPrelude

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

library:
  source-dirs: src

executables:
  json-search-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-search

tests:
  json-search-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-search
